linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - noctx
  disable:
    - all

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: false
