package shell

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

// InitOptions controls shell init script generation options.
type InitOptions struct {
	// NoCdHook disables the auto-activation cd hook in the init script.
	NoCdHook bool
}

// InitScriptData holds the data for the shell init script template.
type InitScriptData struct {
	ShellName  string
	BinaryPath string
	Version    string
	NoCdHook   bool
}

const initScriptTemplate = `# agentenv shell integration for {{.ShellName}}
#
# Generated by agentenv v{{.Version}}
# Usage: eval "$(agentenv init {{.ShellName}})"
#

# Resolve binary path at generation time
_agentenv_binary="{{.BinaryPath}}"

# Simple JSON value parser (no jq dependency)
_agentenv_json_val() {
	local _key="$1"
	local _json="$2"
	echo "$_json" | sed -n 's/.*"'"$_key"'":[[:space:]]*"\([^"]*\)".*/\1/p'
}

# Save current environment for deactivation
_agentenv_save_state() {
	_AGENTENV_SAVED_PS1="${PS1:-}"
}

# Restore environment after deactivation
_agentenv_restore_state() {
	if [ -n "${_AGENTENV_SAVED_PS1:-}" ]; then
		PS1="${_AGENTENV_SAVED_PS1}"
	fi
	unset AGENTENV_ACTIVE
	unset _AGENTENV_SAVED_PS1
}

# p10k custom segment — p10k 自动调用 prompt_agentenv #
prompt_agentenv() {
	if [[ -n "${AGENTENV_ACTIVE:-}" ]]; then
		p10k segment -b black -f 208 -t "agentenv:${AGENTENV_ACTIVE}"
	fi
}

# 非 p10k 兼容 — 通过 precmd 追加到 PS1
_agentenv_preprompt() {
	if [[ -z "${POWERLEVEL9K_MODE:-}" && -n "${AGENTENV_ACTIVE:-}" ]]; then
		PS1="%B%F{208}agentenv:%f%F{cyan}${AGENTENV_ACTIVE}%f%b ${PS1}"
	fi
}

autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd _agentenv_preprompt 2>/dev/null || {
	precmd_functions+=(_agentenv_preprompt)
}

{{- if not .NoCdHook}}
# Auto-activate/deactivate when cd'ing into/out of a directory with agent.yaml
_agentenv_cd_hook() {
	if [ -f "$PWD/agent.yaml" ]; then
		local _env_name
		_env_name="$(basename "$PWD")"
		if [ -d "$HOME/.agentenv/envs/$_env_name" ]; then
			if [ -z "${AGENTENV_ACTIVE:-}" ] || [ "$AGENTENV_ACTIVE" != "$_env_name" ]; then
				agentenv activate "$_env_name" 2>/dev/null || true
			fi
		fi
	elif [ -n "${AGENTENV_ACTIVE:-}" ]; then
		agentenv deactivate 2>/dev/null || true
	fi
}

__agentenv_cd() {
	builtin cd "$@" || return
	_agentenv_cd_hook
}

alias cd=__agentenv_cd
{{end}}
agentenv() {
	if [ $# -eq 0 ]; then
		"$_agentenv_binary"
		return
	fi

	local _cmd="$1"
	shift

	case "$_cmd" in
		activate)
			if [ $# -lt 1 ]; then
				echo "Usage: agentenv activate <name>" >&2
				return 1
			fi
			local _name="$1"
			local _json_output
			_json_output="$("$_agentenv_binary" _internal_activate "$_name" --json 2>/dev/null)" || {
				echo "agentenv: activation failed" >&2
				return 1
			}
			local _active_env
			_active_env="$(_agentenv_json_val "active" "$_json_output")"
			if [ -z "$_active_env" ]; then
				echo "agentenv: activation failed - empty response" >&2
				return 1
			fi
			_agentenv_save_state
			export AGENTENV_ACTIVE="$_active_env"

			if [[ -z "${POWERLEVEL9K_MODE:-}" ]]; then
				export PS1="(agentenv:$_active_env) ${PS1:-}"
			fi
			echo "agentenv: activated environment '$_active_env'" >&2
			;;
		deactivate)
			if [ -z "${AGENTENV_ACTIVE:-}" ]; then
				echo "agentenv: no active environment" >&2
				return 1
			fi
			local _old_env="${AGENTENV_ACTIVE}"
			_agentenv_restore_state
			"$_agentenv_binary" _internal_deactivate --json >/dev/null 2>&1 || true
			echo "agentenv: deactivated environment '$_old_env'" >&2
			;;
		*)
			"$_agentenv_binary" "$_cmd" "$@"
			;;
	esac
}
`

// GenerateInitScript generates a shell init script for the given shell.
// Supported shells: "zsh", "bash".
// Options can be provided via InitOptions to control script features.
func GenerateInitScript(shell string, opts ...InitOptions) (string, error) {
	if shell != "zsh" && shell != "bash" {
		return "", fmt.Errorf("unsupported shell: %s (supported: zsh, bash)", shell)
	}

	binaryPath, err := os.Executable()
	if err != nil {
		binaryPath = "agentenv"
	}

	data := InitScriptData{
		ShellName:  shell,
		BinaryPath: binaryPath,
		Version:    "0.1.0-dev",
	}
	if len(opts) > 0 {
		data.NoCdHook = opts[0].NoCdHook
	}

	tmpl, err := template.New("init").Parse(initScriptTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}
